### ISSUE TITLE
RIP IEX trading API :(

### ISSUE THREAD

**Issue by abtrout** [logitank/smellycat#7]
>  This API will sunset on June 1, 2019. Sign up for IEX Cloud now to avoid disruption.

https://iextrading.com/developer/docs/

Need to find an alternative for [Stocks plugin](https://github.com/logitank/smellycat/blob/master/src/smellycat/plugins/stocks.py#L69-L87).

**Comment by ColCarroll** [comment]
Let's just make things up!
```python
steps = 60 * 12 * 180 # mins/hr * hrs/tradingday * tradingdays/yr
returns = np.cumsum(np.random.randn(steps) + 0.08 / steps)
```

**Comment by abtrout** [comment]
Good idea. I'll keep that in mind for the next time our stock price provider changes!
